=== ppedvAG/XML_Wien_Berlin_30092019/NS/Generiert XmlPad/MeinComputer-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wmh="http://www.wmhelp.com/2003/eGenerator" elementFormDefault="qualified">
  <xs:element name="MeinComputer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Tools"/>
        <xs:element ref="VisualStudio" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="xmlns" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tools">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Tool"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tool">
    <xs:complexType>
      <xs:attribute name="Name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="VisualStudio">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Theme"/>
        <xs:element ref="Extentions"/>
        <xs:element ref="LiveShare"/>
      </xs:sequence>
      <xs:attribute name="xmlns" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Theme" type="xs:string"/>
  <xs:element name="Extentions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Extention" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Extention">
    <xs:complexType>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="MustHave" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="LiveShare">
    <xs:complexType>
      <xs:attribute name="url" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ppedvAG/XML_Wien_Berlin_30092019/NS/Generiert XmlPad/MeinComputer.xml
<?xml version="1.0" encoding="utf-8"?>
<MeinComputer xmlns="http://ppedv.de/xmlKurs/MeinComputer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ppedv.de/xmlKurs/MeinComputer MeinComputer-schema.xsd">

  <Tools>
    <Tool Name="Paint.NET"/>

  </Tools>


  <VisualStudio xmlns="http://ppedv.de/xmlKurs/VS2019">

    <Theme>dark</Theme>

    <Extentions>
      <Extention Name="IntelliCode" MustHave="true"/>
      <Extention Name="Viasfora" MustHave="false"/>
    </Extentions>

    <LiveShare url="https://prod.liveshare.vsengsaas.visualstudio.com/join?D5EB4F09704464E7F5FFADA08C797B33DAAC"/>

  </VisualStudio>

  <VisualStudio xmlns="http://ppedv.de/xmlKurs/VS2017">
    
    <Theme>blue</Theme>
    
    <Extentions>
      <Extention Name="ClippyVS" MustHave="true"/>
    </Extentions>
    
  </VisualStudio>


</MeinComputer>
