=== ppedvAG/XML_Wien_Berlin_30092019/tiere.xsd
<?xml version="1.0"?>
<xsd:schema


  xmlns:xsd="http://www.w3.org/2001/XMLSchema">


<xsd:annotation>
  <xsd:appinfo>Meine Tiere</xsd:appinfo>
  <xsd:documentation xml:lang="en">
  Hier ist definition meiner Tiere
  </xsd:documentation>
</xsd:annotation>


  <xsd:element name="Bezeichnung"  type="xsd:string"/>

  <xsd:element name="Geschlecht"  >
    <xsd:annotation>
      <xsd:documentation>
        Das definiert das Geschlecht des Tieres
      </xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base ="xsd:string">
        <xsd:enumeration value ="Weiblich"/>
        <xsd:enumeration value ="MÃ¤nnlich"/>
        <xsd:enumeration value ="Divers"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>

  <xsd:element name="Name" type="xsd:string"/>

  <xsd:element name="Art">
    <xsd:complexType>
      <xsd:attribute use="required" name ="Gattung" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="AnzahlBeine" >
    <xsd:simpleType>
      <xsd:restriction base="xsd:integer">
        <xsd:maxExclusive value="1000"/>
        <xsd:minExclusive value="1"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>

  <!-- Element mit einfachen Wert und einem Attribute -->
  <xsd:element name="Gewicht" >
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:decimal">
          <xsd:attribute name="Einheit" type="units" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Vegetarier" type="xsd:boolean"/>

  <xsd:element name="Geburtstag" type="xsd:date"/>

  <xsd:element name="Tier">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Bezeichnung" />
        <xsd:element ref="Name" />
        <xsd:element ref="Geschlecht" />
        <xsd:element ref="Art" />
        <xsd:element ref="AnzahlBeine"/>
        <xsd:element ref="Gewicht"/>
        <xsd:element ref="Vegetarier"/>
        <xsd:element ref="Geburtstag"/>
        <xsd:element ref="RegNummer"/>
        <xsd:element ref="Wohnort" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Wohnort" type="location" />

  <xsd:element name="RegNummer">
    <xsd:simpleType >
      <xsd:restriction base="xsd:string">
        <xsd:pattern value="[2][0][0-9][0-9]-[A-Z]{4}-[0-9]{5}-[A-Z]{2}"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>

  <xsd:element name="Tiere" >
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded">
        <xsd:element ref="Tier" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <xsd:simpleType name="units">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="g"/>
      <xsd:enumeration value="kg"/>
      <xsd:enumeration value="t"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="location">
    <xsd:sequence >
      <xsd:element name="Zone" type="xsd:int" />
      <xsd:element name="Bereich" type="xsd:string"/>
      <xsd:element name="Gehege" type="xsd:byte"/>
    </xsd:sequence>
  </xsd:complexType>



</xsd:schema>

=== ppedvAG/XML_Wien_Berlin_30092019/tiere.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="tiereToHTML.xslt"?>
<Tiere xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="tiere.xsd"
       >
  <Tier>

    <Bezeichnung >Affe</Bezeichnung>
    <Name>Emil</Name>
    <Geschlecht>Weiblich</Geschlecht>
    <Art Gattung="Säugetier"/>
    <AnzahlBeine>900</AnzahlBeine>
    <Gewicht Einheit="kg">42.6</Gewicht>
    <Vegetarier>false</Vegetarier>
    <Geburtstag>2013-04-17</Geburtstag>
    <RegNummer>2019-ASBD-00012-GG</RegNummer>
    <Wohnort>
      <Zone>1</Zone>
      <Bereich>Grün</Bereich>
      <Gehege>3</Gehege>
    </Wohnort>
  </Tier>
  <Tier>
    <Bezeichnung>Zebra</Bezeichnung>
    <Name>Bärbel</Name>
    <Geschlecht>Divers</Geschlecht>
    <Art Gattung="Säugetier"></Art>
    <AnzahlBeine>4</AnzahlBeine>
    <Gewicht Einheit="kg">390</Gewicht>
    <Vegetarier>true</Vegetarier>
    <Geburtstag>1996-02-05</Geburtstag>
    <RegNummer>2019-ASBD-00012-GG</RegNummer>
    <Wohnort>
      <Zone>4</Zone>
      <Bereich>Gelb</Bereich>
      <Gehege>29</Gehege>
    </Wohnort>
  </Tier>
  <Tier>
    <Bezeichnung>Löwe</Bezeichnung>
    <Name>Bernd</Name>
    <Geschlecht>Männlich</Geschlecht>
    <Art Gattung="Säugetier"/>
    <AnzahlBeine>4</AnzahlBeine>
    <Gewicht Einheit="kg">195</Gewicht>
    <Vegetarier>false</Vegetarier>
    <Geburtstag>1999-08-22</Geburtstag>
    <RegNummer>2019-ASBD-00012-GG</RegNummer>
    <Wohnort>
      <Zone>1</Zone>
      <Bereich>Rot</Bereich>
      <Gehege>2</Gehege>
    </Wohnort>
  </Tier>
  <Tier>
    <Bezeichnung>Rabe</Bezeichnung>
    <Name>Rudi</Name>
    <Geschlecht>Männlich</Geschlecht>
    <Art Gattung="Vogel"/>
    <AnzahlBeine>2</AnzahlBeine>
    <Gewicht Einheit="g">1254</Gewicht>
    <Vegetarier>false</Vegetarier>
    <Geburtstag>2015-03-29</Geburtstag>
    <RegNummer>2019-ASBD-00012-GG</RegNummer>
    <Wohnort>
      <Zone>6</Zone>
      <Bereich>Blau</Bereich>
      <Gehege>25</Gehege>
    </Wohnort>
  </Tier>
</Tiere>
